(()=>{'use strict';const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const terms=[['Acidité','Sensation vive et structurante en bouche.','Dégustation'],['Arabica','Espèce de caféier appréciée pour sa complexité aromatique.','Botanique'],['Barista','Professionnel de la préparation du café.','Métier'],['Body / Corps','Texture et sensation tactile du café en bouche.','Dégustation'],['Café vert','Graine séchée avant torréfaction.','Transformation'],['Caféine','Alcaloïde stimulant naturellement présent dans le café.','Science'],['Cupping','Dégustation standardisée pour évaluer un café.','Qualité'],['Espresso','Extraction courte sous pression.','Extraction'],['Fermentation','Étape post-récolte pouvant modifier le profil sensoriel.','Transformation'],['Mouture','Taille des particules obtenue par broyage.','Préparation'],['Robusta','Nom courant de Coffea canephora.','Botanique'],['Torréfaction','Transformation thermique du café vert.','Transformation'],['Terroir','Ensemble des facteurs naturels et humains d’un produit agricole.','Culture']];
const recipes=[['Café filtre','Facile','5 min','img/coffee_preparation_modern.png','Une méthode pédagogique pour explorer l’arôme et l’équilibre.'],['Café glacé','Facile','7 min','img/premium_coffee_pour.png','Une préparation fraîche et simple.'],['Espresso tonic','Intermédiaire','5 min','img/coffee_shop_cotonou.png','Une préparation pétillante et contrastée.']];
const state={chat:[],favorites:JSON.parse(localStorage.getItem('cb-favorites')||'[]')};
function toast(t){const x=$('#toast');if(!x)return;x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function nav(){const n=$('#site-nav'),m=$('#mobile-nav'),b=$('#nav-toggle');b?.addEventListener('click',()=>{const o=m.classList.toggle('open');b.setAttribute('aria-expanded',o);document.body.classList.toggle('menu-open',o)});$$('.mobile-link').forEach(a=>a.onclick=()=>{m.classList.remove('open');document.body.classList.remove('menu-open')});window.addEventListener('scroll',()=>n?.classList.toggle('scrolled',scrollY>20),{passive:true});$$('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const t=$(a.getAttribute('href'));if(t){e.preventDefault();t.scrollIntoView({behavior:'smooth'})}}))}
function reveal(){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.08});$$('.reveal').forEach(x=>io.observe(x));const p=$('#progress');addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;p.style.width=(max?scrollY/max*100:0)+'%'},{passive:true})}
function search(){const modal=$('#search-modal'),input=$('#global-search'),box=$('#search-results');const pool=[...$$('section[id]').map(s=>({t:s.querySelector('h2,h1')?.textContent||s.id,d:s.textContent.slice(0,180),id:s.id,type:'Section'})),...terms.map(x=>({t:x[0],d:x[1],id:'dictionnaire',type:'Dictionnaire'})),...recipes.map(x=>({t:x[0],d:x[4],id:'recettes',type:'Recette'}))];function draw(){const q=input.value.trim().toLowerCase(),h=pool.filter(x=>!q||(x.t+' '+x.d).toLowerCase().includes(q)).slice(0,14);box.innerHTML=h.map(x=>`<a class="search-result" href="#${x.id}"><small>${esc(x.type)}</small><b>${esc(x.t)}</b><span>${esc(x.d)}</span></a>`).join('')||'<p class="search-empty">Aucun résultat.</p>'}const open=()=>{modal.classList.add('open');input.focus();draw()},close=()=>modal.classList.remove('open');$('#search-open')?.addEventListener('click',open);$('#search-close')?.addEventListener('click',close);modal?.addEventListener('click',e=>{if(e.target===modal)close()});input?.addEventListener('input',draw);document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();open()}if(e.key==='Escape')close()});draw()}
function dictionary(){const list=$('#dict-list'),input=$('#dict-search'),filter=$('#dict-filter');function draw(){const q=input.value.toLowerCase(),f=filter.value;list.innerHTML=terms.filter(x=>(!q||x.join(' ').toLowerCase().includes(q))&&(!f||x[2]===f)).map(x=>`<article class="dict-card"><div class="dict-meta">${esc(x[2])}<button class="fav" data-id="${esc(x[0])}">☆</button></div><h3>${esc(x[0])}</h3><p>${esc(x[1])}</p></article>`).join('');favs()}input.oninput=draw;filter.onchange=draw;draw()}
function favs(){const save=()=>localStorage.setItem('cb-favorites',JSON.stringify(state.favorites));$$('.fav').forEach(b=>{b.textContent=state.favorites.includes(b.dataset.id)?'★':'☆';b.classList.toggle('active',state.favorites.includes(b.dataset.id));b.onclick=()=>{const i=state.favorites.indexOf(b.dataset.id);i>-1?state.favorites.splice(i,1):state.favorites.push(b.dataset.id);save();favs();renderFavs()}})}function renderFavs(){const x=$('#favorites-list');if(x)x.innerHTML=state.favorites.length?state.favorites.map(v=>`<span class="tag">${esc(v)}</span>`).join(''):'<span class="muted">Aucun favori.</span>'}
function bot(){const form=$('#bot-form'),log=$('#bot-log');if(!form)return;const add=(r,t)=>{const d=document.createElement('div');d.className='chat '+r;d.innerHTML=`<small>${r==='user'?'Vous':'CaféBot'}</small><p>${esc(t).replace(/\n/g,'<br>')}</p>`;log.appendChild(d);log.scrollTop=log.scrollHeight};form.onsubmit=async e=>{e.preventDefault();const i=$('#bot-input'),t=i.value.trim();if(!t)return;i.value='';add('user',t);state.chat.push({role:'user',content:t});try{const r=window.cafeBenin?await window.cafeBenin.chat(state.chat):null;const a=r?.reply||'Le service IA n’est pas disponible actuellement.';state.chat.push({role:'assistant',content:a});add('assistant',a)}catch{add('assistant','Impossible de joindre le service IA. Vérifiez la configuration du backend.')}}}
function recommend(){const f=$('#recommend-form');f?.addEventListener('submit',async e=>{e.preventDefault();const o=$('#recommendation');o.textContent='Analyse…';try{o.textContent=window.cafeBenin?await window.cafeBenin.getAIRecommendation($('#mood').value,$('#prefs').value.split(',').map(x=>x.trim()).filter(Boolean),[]):'Service IA non connecté.'}catch{o.textContent='Service IA indisponible.'}})}
function contact(){const f=$('#comment-form');f?.addEventListener('submit',async e=>{e.preventDefault();const s=$('#comment-status');s.textContent='Envoi…';try{await window.cafeBenin.submitComment($('#comment-name').value,$('#comment-email').value,$('#comment-content').value,'Café Bénin');f.reset();s.textContent='Commentaire envoyé, en attente de modération.'}catch{s.textContent='Échec de l’envoi. Réessayez plus tard.'}})}
addEventListener('DOMContentLoaded',()=>{nav();reveal();search();dictionary();renderFavs();bot();recommend();contact();$('#year').textContent=new Date().getFullYear();});})();