(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const terms=[['Acidité','Sensation vive et structurante en bouche.','Dégustation'],['Arabica','Espèce de caféier appréciée pour sa complexité aromatique.','Botanique'],['Barista','Professionnel de la préparation du café.','Métier'],['Body / Corps','Texture et sensation tactile du café en bouche.','Dégustation'],['Café vert','Graine séchée avant torréfaction.','Transformation'],['Caféine','Alcaloïde stimulant naturellement présent dans le café.','Science'],['Cupping','Dégustation standardisée pour évaluer un café.','Qualité'],['Espresso','Extraction courte sous pression.','Extraction'],['Fermentation','Étape post-récolte pouvant modifier le profil sensoriel.','Transformation'],['Mouture','Taille des particules obtenue par broyage.','Préparation'],['Robusta','Nom courant de Coffea canephora.','Botanique'],['Torréfaction','Transformation thermique du café vert.','Transformation'],['Terroir','Ensemble des facteurs naturels et humains d’un produit agricole.','Culture']];
const recipes=[['Café filtre','Facile','5 min','img/coffee_preparation_modern.png','Une méthode pédagogique pour explorer l’arôme et l’équilibre.'],['Café glacé','Facile','7 min','img/premium_coffee_pour.png','Une préparation fraîche et simple.'],['Espresso tonic','Intermédiaire','5 min','img/coffee_shop_cotonou.png','Une préparation pétillante et contrastée.']];
let favorites=[];try{const parsed=JSON.parse(localStorage.getItem('cb-favorites')||'[]');favorites=Array.isArray(parsed)?parsed.filter(v=>typeof v==='string').slice(0,100):[]}catch{favorites=[]}
const state={chat:[],favorites};
const reduced=()=>window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;
function toast(t){const x=$('#toast');if(!x)return;x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function seo(){const canonical=$('link[rel="canonical"]');const url='https://cafe-benin-info.vercel.app/';if(canonical)canonical.href=url;else{const l=document.createElement('link');l.rel='canonical';l.href=url;document.head.appendChild(l)}let og=$('meta[property="og:url"]');if(!og){og=document.createElement('meta');og.setAttribute('property','og:url');document.head.appendChild(og)}og.content=url}
function nav(){const n=$('#site-nav'),m=$('#mobile-nav'),b=$('#nav-toggle');b?.addEventListener('click',()=>{const o=m?.classList.toggle('open');b.setAttribute('aria-expanded',String(!!o));document.body.classList.toggle('menu-open',!!o)});$$('.mobile-link').forEach(a=>a.addEventListener('click',()=>{m?.classList.remove('open');document.body.classList.remove('menu-open')}));window.addEventListener('scroll',()=>n?.classList.toggle('scrolled',scrollY>20),{passive:true});$$('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const target=$(a.getAttribute('href'));if(target){e.preventDefault();target.scrollIntoView({behavior:reduced()?'auto':'smooth'})}}))}
function reveal(){if(!('IntersectionObserver'in window)){ $$('.reveal').forEach(x=>x.classList.add('in'));return }const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.08});$$('.reveal').forEach(x=>io.observe(x));const p=$('#progress');if(p)window.addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;p.style.width=(max?Math.min(100,scrollY/max*100):0)+'%'},{passive:true})}
function search(){const modal=$('#search-modal'),input=$('#global-search'),box=$('#search-results');if(!modal||!input||!box)return;const pool=[...$$('section[id]').map(s=>({t:s.querySelector('h2,h1')?.textContent||s.id,d:s.textContent.slice(0,180),id:s.id,type:'Section'})),...terms.map(x=>({t:x[0],d:x[1],id:'dictionnaire',type:'Dictionnaire'})),...recipes.map(x=>({t:x[0],d:x[4],id:'recettes',type:'Recette'}))];const draw=()=>{const q=input.value.trim().toLowerCase(),h=pool.filter(x=>!q||(x.t+' '+x.d).toLowerCase().includes(q)).slice(0,14);box.innerHTML=h.map(x=>`<a class="search-result" href="#${x.id}"><small>${esc(x.type)}</small><b>${esc(x.t)}</b><span>${esc(x.d)}</span></a>`).join('')||'<p class="search-empty">Aucun résultat.</p>'};const close=()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('menu-open')};const open=()=>{modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('menu-open');draw();input.focus()};$('#search-open')?.addEventListener('click',open);$('#search-close')?.addEventListener('click',close);modal.addEventListener('click',e=>{if(e.target===modal)close();if(e.target.closest('.search-result'))close()});input.addEventListener('input',draw);document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();open()}if(e.key==='Escape')close()});draw()}
function dictionary(){const list=$('#dict-list'),input=$('#dict-search'),filter=$('#dict-filter');if(!list||!input||!filter)return;const draw=()=>{const q=input.value.toLowerCase(),f=filter.value;list.innerHTML=terms.filter(x=>(!q||x.join(' ').toLowerCase().includes(q))&&(!f||x[2]===f)).map(x=>`<article class="dict-card"><div class="dict-meta">${esc(x[2])}<button type="button" class="fav" aria-label="Ajouter ${esc(x[0])} aux favoris" data-id="${esc(x[0])}">☆</button></div><h3>${esc(x[0])}</h3><p>${esc(x[1])}</p></article>`).join('');bindFavorites();renderFavs()};input.addEventListener('input',draw);filter.addEventListener('change',draw);draw()}
function saveFavs(){try{localStorage.setItem('cb-favorites',JSON.stringify(state.favorites))}catch{toast('Impossible de sauvegarder les favoris sur cet appareil.')}}
function bindFavorites(){$$('.fav').forEach(b=>{const active=state.favorites.includes(b.dataset.id);b.textContent=active?'★':'☆';b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));b.onclick=()=>{const id=b.dataset.id,i=state.favorites.indexOf(id);if(i>-1)state.favorites.splice(i,1);else if(state.favorites.length<100)state.favorites.push(id);saveFavs();dictionary();}})}
function renderFavs(){const x=$('#favorites-list');if(x)x.innerHTML=state.favorites.length?state.favorites.map(v=>`<span class="tag">${esc(v)}</span>`).join(''):'<span class="muted">Aucun favori.</span>'}
function share(){document.querySelectorAll('[data-share]').forEach(button=>button.addEventListener('click',async()=>{const section=button.closest('section'),title=section?.querySelector('h2')?.textContent?.replace(/\s+/g,' ').trim()||'Café Bénin',url=`${location.origin}${location.pathname}#${section?.id||'recettes'}`;try{if(navigator.share)await navigator.share({title:'Café Bénin',text:title,url});else{await navigator.clipboard.writeText(url);toast('Lien copié.')}}catch(error){if(error?.name!=='AbortError')toast('Impossible de partager ce lien.')}}))}
function bot(){const form=$('#bot-form'),log=$('#bot-log');if(!form||!log)return;const add=(r,t)=>{const d=document.createElement('div');d.className='chat '+r;d.innerHTML=`<small>${r==='user'?'Vous':'CaféBot'}</small><p>${esc(t).replace(/\n/g,'<br>')}</p>`;log.appendChild(d);log.scrollTop=log.scrollHeight};form.addEventListener('submit',async e=>{e.preventDefault();const i=$('#bot-input'),t=i.value.trim();if(!t||t.length>4000)return;i.value='';add('user',t);state.chat.push({role:'user',content:t});state.chat=state.chat.slice(-20);try{if(!window.cafeBenin)throw new Error('Backend absent');const r=await window.cafeBenin.chat(state.chat),a=r?.reply||'Le service IA n’est pas disponible actuellement.';state.chat.push({role:'assistant',content:a});add('assistant',a)}catch{add('assistant','Impossible de joindre le service IA. Réessayez dans quelques instants.')}})}
function recommend(){const f=$('#recommend-form');f?.addEventListener('submit',async e=>{e.preventDefault();const o=$('#recommendation'),m=$('#mood')?.value.trim();if(!m||m.length>200)return;o.textContent='Analyse…';try{if(!window.cafeBenin)throw new Error('Backend absent');o.textContent=await window.cafeBenin.getAIRecommendation(m,$('#prefs').value.split(',').map(x=>x.trim()).filter(Boolean),[])}catch{o.textContent='Service IA indisponible. Réessayez plus tard.'}})}
function contact(){const f=$('#comment-form');f?.addEventListener('submit',async e=>{e.preventDefault();const s=$('#comment-status');s.textContent='Envoi…';try{if(!window.cafeBenin)throw new Error('Backend absent');await window.cafeBenin.submitComment($('#comment-name').value,$('#comment-email').value,$('#comment-content').value,'Café Bénin');f.reset();s.textContent='Commentaire envoyé, en attente de modération.'}catch{s.textContent='Échec de l’envoi. Vérifiez votre connexion puis réessayez.'}})}
addEventListener('DOMContentLoaded',()=>{seo();nav();reveal();search();dictionary();renderFavs();bot();recommend();contact();share();const year=$('#year');if(year)year.textContent=new Date().getFullYear()});
})();